import { describe, expect, test } from 'vitest';
import { renameTableInSchema } from '@/utils/common.ts';
import manyToManySchema from '@/schema-infos/manyToMany.ts';
import oneToOneSchema from '@/schema-infos/oneToOne.ts';
import oneToManySchema from '@/schema-infos/oneToMany.ts';

describe('renameTableInSchema', () => {
  test('should rename order table to orderz and update all related references', () => {
    const result = renameTableInSchema({
      oldTableName: 'order',
      newTableName: 'orderz',
      schemaInfo: manyToManySchema,
    });

    expect(result).toEqual([
      {
        tableName: 'product',
        requiredColumns: ['product_id', 'product_name'],
        columnsInfo: [
          {
            column_name: 'product_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'product_name',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
        ],
        foreignTables: [],
        foreignKeys: [],
        isPivot: false,
        childTables: ['orderz_product'],
        hasOne: [],
        hasMany: ['orderz_product'],
        belongsTo: [],
        belongsToMany: ['orderz'],
        pivotRelationships: [
          {
            relatedTable: 'orderz',
            pivotTable: 'orderz_product',
          },
        ],
      },
      {
        tableName: 'customer',
        requiredColumns: ['customer_id', 'name'],
        columnsInfo: [
          {
            column_name: 'customer_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'name',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
        ],
        foreignTables: [],
        foreignKeys: [],
        isPivot: false,
        childTables: ['orderz'],
        hasOne: [],
        hasMany: ['orderz'],
        belongsTo: [],
        belongsToMany: [],
        pivotRelationships: [],
      },
      {
        tableName: 'orderz',
        requiredColumns: ['orderz_id', 'customer_id'],
        columnsInfo: [
          {
            column_name: 'orderz_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'customer_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: {
              foreign_table_name: 'customer',
              foreign_column_name: 'customer_id',
            },
          },
        ],
        foreignTables: ['customer'],
        foreignKeys: ['customer_id'],
        isPivot: false,
        childTables: ['orderz_product'],
        hasOne: [],
        hasMany: ['orderz_product'],
        belongsTo: ['customer'],
        belongsToMany: ['product'],
        pivotRelationships: [
          {
            relatedTable: 'product',
            pivotTable: 'orderz_product',
          },
        ],
      },
      {
        tableName: 'orderz_product',
        requiredColumns: ['orderz_product_id', 'orderz_id', 'product_id'],
        columnsInfo: [
          {
            column_name: 'orderz_product_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'orderz_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: {
              foreign_table_name: 'orderz',
              foreign_column_name: 'orderz_id',
            },
          },
          {
            column_name: 'product_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: {
              foreign_table_name: 'product',
              foreign_column_name: 'product_id',
            },
          },
        ],
        foreignTables: ['orderz', 'product'],
        foreignKeys: ['orderz_id', 'product_id'],
        isPivot: true,
        childTables: [],
        hasOne: [],
        hasMany: [],
        belongsTo: ['orderz', 'product'],
        belongsToMany: [],
        pivotRelationships: [],
      },
    ]);
  });

  test('should rename product table to productz and update all related references', () => {
    const result = renameTableInSchema({
      oldTableName: 'product',
      newTableName: 'productz',
      schemaInfo: manyToManySchema,
    });

    expect(result).toEqual([
      {
        tableName: 'productz',
        requiredColumns: ['productz_id', 'product_name'],
        columnsInfo: [
          {
            column_name: 'productz_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'product_name',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
        ],
        foreignTables: [],
        foreignKeys: [],
        isPivot: false,
        childTables: ['order_productz'],
        hasOne: [],
        hasMany: ['order_productz'],
        belongsTo: [],
        belongsToMany: ['order'],
        pivotRelationships: [
          {
            relatedTable: 'order',
            pivotTable: 'order_productz',
          },
        ],
      },
      {
        tableName: 'customer',
        requiredColumns: ['customer_id', 'name'],
        columnsInfo: [
          {
            column_name: 'customer_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'name',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
        ],
        foreignTables: [],
        foreignKeys: [],
        isPivot: false,
        childTables: ['order'],
        hasOne: [],
        hasMany: ['order'],
        belongsTo: [],
        belongsToMany: [],
        pivotRelationships: [],
      },
      {
        tableName: 'order',
        requiredColumns: ['order_id', 'customer_id'],
        columnsInfo: [
          {
            column_name: 'order_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'customer_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: {
              foreign_table_name: 'customer',
              foreign_column_name: 'customer_id',
            },
          },
        ],
        foreignTables: ['customer'],
        foreignKeys: ['customer_id'],
        isPivot: false,
        childTables: ['order_productz'],
        hasOne: [],
        hasMany: ['order_productz'],
        belongsTo: ['customer'],
        belongsToMany: ['productz'],
        pivotRelationships: [
          {
            relatedTable: 'productz',
            pivotTable: 'order_productz',
          },
        ],
      },
      {
        tableName: 'order_productz',
        requiredColumns: ['order_productz_id', 'order_id', 'productz_id'],
        columnsInfo: [
          {
            column_name: 'order_productz_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'order_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: {
              foreign_table_name: 'order',
              foreign_column_name: 'order_id',
            },
          },
          {
            column_name: 'productz_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: {
              foreign_table_name: 'productz',
              foreign_column_name: 'productz_id',
            },
          },
        ],
        foreignTables: ['order', 'productz'],
        foreignKeys: ['order_id', 'productz_id'],
        isPivot: true,
        childTables: [],
        hasOne: [],
        hasMany: [],
        belongsTo: ['order', 'productz'],
        belongsToMany: [],
        pivotRelationships: [],
      },
    ]);
  });

  test('should rename user table to userz and update all related references', () => {
    const result = renameTableInSchema({
      oldTableName: 'user',
      newTableName: 'userz',
      schemaInfo: oneToOneSchema,
    });

    expect(result).toEqual([
      {
        tableName: 'userz',
        requiredColumns: [
          'userz_id',
          'first_name',
          'last_name',
          'email',
          'username',
          'password',
          'created_at',
          'updated_at',
        ],
        columnsInfo: [
          {
            column_name: 'userz_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'first_name',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'last_name',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'email',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: true,
            foreign_key: null,
          },
          {
            column_name: 'username',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: true,
            foreign_key: null,
          },
          {
            column_name: 'password',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'created_at',
            data_type: 'Date',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'updated_at',
            data_type: 'Date',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
        ],
        foreignTables: [],
        foreignKeys: [],
        isPivot: false,
        childTables: ['post'],
        hasOne: ['post'],
        hasMany: [],
        belongsTo: [],
        belongsToMany: [],
        pivotRelationships: [],
      },
      {
        tableName: 'post',
        requiredColumns: [
          'post_id',
          'userz_id',
          'title',
          'created_at',
          'updated_at',
        ],
        columnsInfo: [
          {
            column_name: 'post_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'userz_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: true,
            foreign_key: {
              foreign_table_name: 'userz',
              foreign_column_name: 'userz_id',
            },
          },
          {
            column_name: 'title',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'content',
            data_type: 'string',
            is_nullable: 'YES',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'created_at',
            data_type: 'Date',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'updated_at',
            data_type: 'Date',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
        ],
        foreignTables: ['userz'],
        foreignKeys: ['userz_id'],
        isPivot: false,
        childTables: [],
        hasOne: [],
        hasMany: [],
        belongsTo: ['userz'],
        belongsToMany: [],
        pivotRelationships: [],
      },
    ]);
  });

  test('should rename post table to postz in one-to-many schema', () => {
    const result = renameTableInSchema({
      oldTableName: 'post',
      newTableName: 'postz',
      schemaInfo: oneToManySchema,
    });

    expect(result).toEqual([
      {
        tableName: 'user',
        requiredColumns: [
          'user_id',
          'first_name',
          'last_name',
          'email',
          'username',
          'password',
          'created_at',
          'updated_at',
        ],
        columnsInfo: [
          {
            column_name: 'user_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'first_name',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'last_name',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'email',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: true,
            foreign_key: null,
          },
          {
            column_name: 'username',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: true,
            foreign_key: null,
          },
          {
            column_name: 'password',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'created_at',
            data_type: 'Date',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'updated_at',
            data_type: 'Date',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
        ],
        foreignTables: [],
        foreignKeys: [],
        isPivot: false,
        childTables: ['postz'],
        hasOne: [],
        hasMany: ['postz'],
        belongsTo: [],
        belongsToMany: [],
        pivotRelationships: [],
      },
      {
        tableName: 'postz',
        requiredColumns: [
          'postz_id',
          'user_id',
          'title',
          'created_at',
          'updated_at',
        ],
        columnsInfo: [
          {
            column_name: 'postz_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: 'AUTO_INCREMENT',
            primary_key: true,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'user_id',
            data_type: 'number',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: {
              foreign_table_name: 'user',
              foreign_column_name: 'user_id',
            },
          },
          {
            column_name: 'title',
            data_type: 'string',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'content',
            data_type: 'string',
            is_nullable: 'YES',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'created_at',
            data_type: 'Date',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
          {
            column_name: 'updated_at',
            data_type: 'Date',
            is_nullable: 'NO',
            column_default: null,
            primary_key: false,
            unique: false,
            foreign_key: null,
          },
        ],
        foreignTables: ['user'],
        foreignKeys: ['user_id'],
        isPivot: false,
        childTables: [],
        hasOne: [],
        hasMany: [],
        belongsTo: ['user'],
        belongsToMany: [],
        pivotRelationships: [],
      },
    ]);
  });
});
