import { ISchemaInfo } from '@/interfaces/interfaces';

export const oneToMany: ISchemaInfo[] = [
  {
    table: 'user',
    requiredColumns: [
      'user_id',
      'first_name',
      'last_name',
      'email',
      'username',
      'password',
      'created_at',
      'updated_at',
    ],
    columnsInfo: [
      {
        column_name: 'user_id',
        data_type: 'number',
        is_nullable: 'NO',
        column_default: 'AUTO_INCREMENT',
        primary_key: true,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'first_name',
        data_type: 'string',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'last_name',
        data_type: 'string',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'email',
        data_type: 'string',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: true,
        foreign_key: null,
      },
      {
        column_name: 'username',
        data_type: 'string',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: true,
        foreign_key: null,
      },
      {
        column_name: 'password',
        data_type: 'string',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'created_at',
        data_type: 'Date',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'updated_at',
        data_type: 'Date',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
    ],
    foreignTables: [],
    foreignKeys: [],
    isPivot: false,
    childTables: ['post'],
    hasOne: [],
    hasMany: ['post'],
    belongsTo: [],
    belongsToMany: [],
    pivotRelationships: [],
  },
  {
    table: 'post',
    requiredColumns: [
      'post_id',
      'user_id',
      'title',
      'created_at',
      'updated_at',
    ],
    columnsInfo: [
      {
        column_name: 'post_id',
        data_type: 'number',
        is_nullable: 'NO',
        column_default: 'AUTO_INCREMENT',
        primary_key: true,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'user_id',
        data_type: 'number',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: {
          foreign_table_name: 'user',
          foreign_column_name: 'user_id',
        },
      },
      {
        column_name: 'title',
        data_type: 'string',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'content',
        data_type: 'string',
        is_nullable: 'YES',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'created_at',
        data_type: 'Date',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
      {
        column_name: 'updated_at',
        data_type: 'Date',
        is_nullable: 'NO',
        column_default: null,
        primary_key: false,
        unique: false,
        foreign_key: null,
      },
    ],
    foreignTables: ['user'],
    foreignKeys: ['user_id'],
    isPivot: false,
    childTables: [],
    hasOne: [],
    hasMany: [],
    belongsTo: ['user'],
    belongsToMany: [],
    pivotRelationships: [],
  },
];
