export const PROJECT_ACTIONS = {
  CREATE_FILE: 'CREATE_FILE',
  CREATE_MULTIPLE_FILES: 'CREATE_MULTIPLE_FILES',
  FOR_EACH_TABLE: 'FOR_EACH_TABLE',
} as const;

export type ProjectAction =
  (typeof PROJECT_ACTIONS)[keyof typeof PROJECT_ACTIONS];
