export const PROJECT_ACTIONS = {
  CREATE_FILE: 'CREATE_FILE',
  CREATE_BASE_METHOD_FILE: 'CREATE_BASE_METHOD_FILE',
  FILE_LOOP: 'FILE_LOOP',
  FOLDER_LOOP: 'FOLDER_LOOP',
  LOOP_FOLDERS: 'LOOP_FOLDERS',
  IMPORT_PROJECT: 'IMPORT_PROJECT',
} as const;

export type ProjectAction =
  (typeof PROJECT_ACTIONS)[keyof typeof PROJECT_ACTIONS];

export const IMPORT_PROJECT_REGEX = new RegExp(
  `${PROJECT_ACTIONS.IMPORT_PROJECT}\\((.*?)\\)$`,
);
