export const PROJECT_ACTIONS = {
  CREATE_FILE: 'CREATE_FILE',
  CREATE_MULTIPLE_FILES: 'CREATE_MULTIPLE_FILES',
  CREATE_DYNAMIC_FOLDERS: 'CREATE_DYNAMIC_FOLDERS',
} as const;

export type ProjectAction =
  (typeof PROJECT_ACTIONS)[keyof typeof PROJECT_ACTIONS];
