events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream laravel {
        server laravel:9000;
    }

    server {
        listen 80;
        server_name localhost;

        client_max_body_size 100M;

        location /laravel {
            rewrite ^/laravel/?(.*)$ /$1 break;
            root /var/www/html/public;
            index index.php index.html;
            
            try_files $uri $uri/ /index.php?$query_string;

            location ~ \.php$ {
                fastcgi_pass laravel;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
                include fastcgi_params;
                fastcgi_param PATH_INFO $fastcgi_path_info;
            }
        }

        location / {
            return 404;
        }
    }
}

