[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:vite]
command=bunx --bun vite --host 0.0.0.0 --port 3000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PATH="/usr/local/bin:/usr/bin:/bin",NODE_ENV="development",VITE_FRONTEND_PORT="3000",VITE_BACKEND_PORT="5000",VITE_BACKEND_HOST="http://localhost",VITE_API_URL="api",VITE_FRONTEND_URL="http://localhost:1214"

[program:hono]
command=bun --hot src/index.ts
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PATH="/usr/local/bin:/usr/bin:/bin",NODE_ENV="development",VITE_FRONTEND_PORT="3000",VITE_BACKEND_PORT="5000",VITE_BACKEND_HOST="http://localhost",VITE_API_URL="api",VITE_FRONTEND_URL="http://localhost:1214",VERCEL=""

