import type { IStructure } from '@/components/FileViewer.tsx';
import {
  AgentScaffoldRequestSchema,
  ScaffoldContextSchema,
  type IAgentScaffoldRequest,
} from '@/schemas/agentScaffold.ts';
import { z } from 'zod';
import { AgentScaffoldExportError } from '@/utils/agentScaffoldExport.ts';

export interface IScaffoldProvenanceInput {
  templateSource?: string;
  templateSha?: string;
  recipeSha?: string;
  generatorSha?: string;
  delivery?: 'api' | 'local-directory';
}

function commitOrNull(value: string | undefined): string | null {
  return value !== undefined && /^[a-f\d]{40}$/i.test(value)
    ? value.toLowerCase()
    : null;
}

export function createScaffoldMetadata(
  input: IAgentScaffoldRequest,
  sources: IScaffoldProvenanceInput,
) {
  const output = input.output ?? 'github_pr';
  const request: IAgentScaffoldRequest = {
    schemaInfo: input.schemaInfo,
    ...(input.project_url === undefined
      ? { project: input.project }
      : { project_url: input.project_url }),
    ...(input.template_repo === undefined
      ? {}
      : { template_repo: input.template_repo }),
    output,
    ...(output === 'github_pr'
      ? {
          target_repo: input.target_repo,
          create_repo: false,
          draft: true,
          ...(input.prNumber === undefined ? {} : { prNumber: input.prNumber }),
          ...(input.prUrl === undefined ? {} : { prUrl: input.prUrl }),
          ...(input.branch === undefined ? {} : { branch: input.branch }),
        }
      : input.files === undefined
        ? {}
        : { files: input.files }),
  };
  return {
    manifestVersion: 1,
    request,
    provenance: {
      generator: {
        repository: 'https://github.com/judigot/scaffolder',
        commitSha: commitOrNull(sources.generatorSha),
        delivery: sources.delivery ?? 'api',
      },
      recipe: {
        source: input.project_url ?? input.project ?? null,
        resolvedSha: commitOrNull(sources.recipeSha),
      },
      template: {
        source: sources.templateSource ?? input.template_repo ?? null,
        resolvedSha: commitOrNull(sources.templateSha),
      },
    },
    context: {
      documents: input.context?.documents ?? [],
      unresolvedDecisions: input.context?.unresolvedDecisions ?? [],
      ...(input.context?.scope === undefined
        ? {}
        : { scope: input.context.scope }),
      regeneration: [
        'Extract request and merge documents, unresolvedDecisions and scope into context; never send the whole manifest.',
        'Edit schemaInfo and satisfy the selected recipe filter; extra tables may not be generated by an auth-only recipe.',
        'Use provenance commits to pin sources for an exact replay. Null means the revision was not recorded.',
        'Use runtime credentials only; never store secrets here.',
        'Inspect branch-only changes before API regeneration. Only generated manifest.json is re-emitted automatically.',
        'Regenerate into a new directory; fix recipes or the generator, not generated application files.',
        'Run fresh application checks and record new results; generation validation is not production readiness.',
      ],
    },
    verification: {
      generation: 'passed',
      applicationChecks: [],
    },
  };
}

export function scaffoldManifestToRequest(
  value: unknown,
): IAgentScaffoldRequest {
  const manifest = z
    .object({
      manifestVersion: z.literal(1),
      request: AgentScaffoldRequestSchema,
      context: ScaffoldContextSchema.strip().optional(),
    })
    .parse(value);
  return { ...manifest.request, context: manifest.context };
}

export function addScaffoldMetadata(
  structure: IStructure,
  metadata: ReturnType<typeof createScaffoldMetadata>,
): IStructure {
  const existing = structure.find((item) => item.name === '.scaffolder');
  if (
    existing?.type === 'file' ||
    (existing?.type === 'folder' &&
      existing.children.some(
        (item) => item.name === 'manifest.json' && item.type !== 'file',
      ))
  ) {
    throw new AgentScaffoldExportError(
      'Reserved scaffolding manifest path conflicts with generated content.',
      'INVALID_EXPORT_PATH',
    );
  }
  return [
    ...structure.filter((item) => item.name !== '.scaffolder'),
    {
      type: 'folder',
      name: '.scaffolder',
      children: [
        ...(existing?.type === 'folder'
          ? existing.children.filter((item) => item.name !== 'manifest.json')
          : []),
        {
          type: 'file',
          name: 'manifest.json',
          content: `${JSON.stringify(metadata, null, 2)}\n`,
        },
      ],
    },
  ];
}
