import { Router } from 'express';
import executeCustomSchemaRouter from './executeCustomSchema';
import scaffoldRouter from './scaffold';
import introspectRouter from './introspect';
import userFilesRouter from './getUserFiles';
import getUserFilesFromPublicRepoRouter from './getUserFilesFromPublicRepo';
import createLocalFilesRouter from './createLocalFiles';
import createGitHubFileRouter from './createGitHubFile';
import createGitHubRepositoryRouter from './createGitHubRepository';
import createGitHubFolderStructureRouter from './createGitHubFolderStructure';
import githubTokenRouter from './githubToken';
import userMetadataRouter from './userMetadata';
import helloRouter from './hello';
const router = Router();
router.use(helloRouter);
router.use(executeCustomSchemaRouter);
router.use(scaffoldRouter);
router.use(introspectRouter);
router.use(userFilesRouter);
router.use(getUserFilesFromPublicRepoRouter);
router.use(createLocalFilesRouter);
router.use(createGitHubFileRouter);
router.use(createGitHubRepositoryRouter);
router.use(createGitHubFolderStructureRouter);
router.use(githubTokenRouter);
router.use(userMetadataRouter);
export default router;
